# Generated by Django 3.2 on 2021-05-05 07:44

from django.db import migrations, models
import profanitycustom.validators


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_alter_comment_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.CharField(max_length=1000, validators=[profanitycustom.validators.validate_is_profane]),
        ),
    ]
