# Generated by Django 3.2 on 2021-05-05 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20210505_0827'),
        ('posts', '0008_alter_post_content'),
    ]

    operations = [
    ]
