# Generated by Django 3.2 on 2021-05-06 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_merge_0003_auto_20210505_0827_0008_alter_post_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='created_at',
        ),
    ]
