# Generated by Django 3.2 on 2021-05-04 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msgnotifications', '0002_notification_notifytype'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='instance_id',
            field=models.CharField(default='', max_length=4),
            preserve_default=False,
        ),
    ]
