# Generated by Django 3.2 on 2021-05-06 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msgnotifications', '0004_notification_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='read',
            field=models.BooleanField(default=False),
        ),
    ]
