# Generated by Django 3.2 on 2021-05-04 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0005_remove_group_members'),
        ('accounts', '0004_auto_20210502_2249'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='groups',
            field=models.ManyToManyField(blank=True, null=True, to='groups.Group'),
        ),
    ]
