# Generated by Django 3.2 on 2021-05-04 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_userprofile_email'),
        ('accounts', '0005_userprofile_groups'),
    ]

    operations = [
    ]
