# Generated by Django 3.2 on 2021-05-04 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20210504_1510'),
        ('accounts', '0006_merge_0005_userprofile_email_0005_userprofile_groups'),
    ]

    operations = [
    ]
