# Generated by Django 3.2 on 2021-05-06 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendrequest',
            name='timestamp',
        ),
    ]
