# Generated by Django 3.2 on 2021-05-02 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_alter_group_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='group',
            name='description',
            field=models.CharField(default='jhgdfuysgyufg', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='group',
            name='privacy',
            field=models.CharField(choices=[('pub', 'public'), ('fr', 'friends')], default='public', max_length=300),
            preserve_default=False,
        ),
    ]
