# Generated by Django 3.2 on 2021-05-02 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('groups', '0003_auto_20210502_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(blank=True, null=True, to='accounts.UserProfile'),
        ),
    ]
