# Generated by Django 3.2 on 2021-05-04 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0004_group_members'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='members',
        ),
    ]
