# Generated by Django 3.2 on 2021-05-04 19:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('groups', '0005_remove_group_members'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groupinvitegroup', to='groups.group')),
                ('inviteFrom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groupinvitefrom', to=settings.AUTH_USER_MODEL)),
                ('inviteTo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groupinviteto', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
