# Generated by Django 3.2 on 2021-05-06 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0007_grouprequestjoin'),
        ('groups', '0007_remove_groupinvite_created_at'),
    ]

    operations = [
    ]
