# Generated by Django 3.2 on 2021-05-06 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0008_merge_20210506_0131'),
        ('groups', '0008_merge_20210506_1507'),
    ]

    operations = [
    ]
