# Generated by Django 3.2 on 2021-05-06 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0009_merge_20210506_2050'),
        ('groups', '0009_merge_20210506_2107'),
    ]

    operations = [
    ]
